#!/bin/bash
# ========================================
#	HEADER
# ========================================

# Author: Indranil Sen
# 
# This script creates a boilerplate for an
# AngularJS web app.

version="1.1.0"

# ========================================
#	FLAGS
# ========================================

# Defaults
silent=0
saveLog=0
initTemp=0
passedArgs=()

while [ ! $# -eq 0 ]; do
case "$1" in
	--help | -h)
		echo -n -e "\nmake-webapp [OPTION]... [FILE]...

	This script creates a boilerplate project for an AngularJS web app.	

	Options:
	-h, --help                       Print usage information
	-n, --name    [project_name]     Name of project
	-t, --template					 Initialize project with a template
	-l, --logfile [path]             Specify path for log file as parameter
	-s, --silent                     Do not print log messages to standard output
	-v, --version                    Prints script version to standard output

	If the -l, --logfile [path] is specified, the script creates a logfile
	of the script processes.\n\n"
		exit
		;;
	--version | -v)
		echo "$version"
		exit
		;;
	--name | -n)
		passedArgs+=("n")
		shift
		projectName="${1}"
		if [ -z "$projectName" ]; then
			echo "Specify project name."
			exit
		fi
		;;
	--template | -t)
		passedArgs+=("t")
		initTemp=1
		;;
	--logfile | -l)
		passedArgs+=("l")
		shift
		LOG_FILE="${1}"
		if [ -z "$LOG_FILE" ]; then
			echo "Specify path to log file."
			exit
		fi
		if [ ! -d "$LOG_FILE" ]; then
			echo "Invalid path."
			exit
		fi
		LOG_FILE="$LOG_FILE/runlog.log"
		saveLog=1
		;;
	--silent | -s)
		passedArgs+=("s")
		silent=1
		;;
esac
shift
done

# ========================================
#	VARIABLES
# ========================================
scriptName="${BASH_SOURCE[0]}"
scriptPath="$(cd "$(dirname "scriptName" )" && pwd)"

root="$(pwd)/$projectName"

homebrewDependencies=("node")
install=()

nodeDevDependencies=("gulp" "gulp-autoprefixer")
nodeProdDependencies=()

blue=$(tput setaf 4)
cyan=$(tput setaf 6)
red=$(tput setaf 1)
pink=$(tput setaf 5)
yellow=$(tput setaf 3)
colorReset=$(tput sgr0)
# ========================================
#	FUNCTIONS
# ========================================

# Checking Homebrew Package Installation
# --------------------
# Checking is homebrew is installed. In not found, 
# the script will install homebrew.
# --------------------
findBrew() {
	if [ $(which brew 2>/dev/null) ]; then
		log -m Homebrew available
	else
		log -e Homebrew not found. Now installing ...
		/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
		log -m Homebrew installed
	fi
}

# Checking for Homebrew Dependencies
# --------------------
# Dependencies for running the webapp are listed in the
# arrays. If not found, the dependices are installed.
# --------------------
checkBrewDependencies() {
	log -m Checking for brew dependices ...
	for pkg in ${homebrewDependencies[@]}
	do
		if [ $(which $pkg 2>/dev/null) ]; then
			continue
		else
			log -e "$pkg not installed"
			install+=("$pkg")
		fi
	done

}

# Installing Homebrew Dependencies
# --------------------
# Dependencies for running the webapp are installed using homebrew
# --------------------
installBrewDependencies() {
	for pkg in ${install[@]}
	do
		"$(brew install "$pkg")"
	done

	if [ ${#install[@]} -gt 0 ]; then
		log -m Brew dependencies installed
	else
		log -m Brew dependencies alreadly installed
	fi
}

# Installing Node Dependencies
# --------------------
# Dev and prod dependencies are installed using npm
# --------------------
installNpmDependencies() {
	log -m Installing node packages ...
	for devPkg in ${nodeDevDependencies[@]}
	do
		"$(npm install --save-dev "$devPkg")"
	done

	for prodPkg in ${nodeProdDependencies[@]}
	do
		"$(npm install --save "$prodPkg")"
	done
	log -m Node packages installed
}

# Log Messages
# --------------------
# Logs messags to standard output. Three types of messages
# can be logged:
#	e: error messages
#	m: general message
# 	l: activity log messages
#	n: unformatted, normal messages (not logged to log file)
# Each type is displayed differently. If a log file directory is 
# specied by --logfile '~/directory', then any log message will 
# be piped to the log file.
# Logged messages are not output to standard output if the --silent
# flag is specified.
# --------------------
log() {
	TAG=""
	TIMESTAMP="$(date +"%Y-%m-%d:%H:%M:%S")"
	cleanPrint=false
	local OPTIND;
	while getopts "e:m:l:n:" option
	do
		case "${option}" in
			m) TAG="$yellow[MSG] ";;	
			e) TAG="$red[ERR] ";;
			l) TAG="$cyan[LOG] ";;
			n) TAG=""; cleanPrint=true;;
			*) echo 'Incorrect log usage. Flag required.'; exit;;
		esac

		shift

		# Only print to log file, if a log file is specified in program 
		# argument AND the messaged to be logged has either m, e or l flag
		if [ $saveLog -eq 1 ] && [ $cleanPrint = false ]; then
				echo -e "${TAG:5}[$TIMESTAMP]:\n$@\n" >> $LOG_FILE
		elif [ $silent -eq 0 ]; then
			echo "$TAG$colorReset$@"
		fi
	done
}

# Checking Required Arguments
# --------------------
# Required arguments are checked. If they are not passed, the program exits gracefully.
# --------------------
checkReqArgs() {
	required=('n:Project name required.')
	valid=0
	for ((i = 0; i < ${#required[@]}; i++))
	do
		flag="${required[$i]:0:1}"
		msg="${required[$i]:2}"
		found=false
		for ((j = 0; j < ${#passedArgs[@]}; j++))
		do
			if [ $flag == ${passedArgs[$j]} ]; then
				((valid++))
				found=true
				break
			else
				found=false
			fi
		done

		if [ $found == false ]; then
			case "$flag" in
				n)  read -p "Project name? " projectName
					while [[ -z "$projectName" ]]; do
						read -p "Answer required: " projectName
					done
					root="$(pwd)/$projectName"
					;;
			esac
		fi

	done

	if [ $valid -eq ${#required[@]} ]; then
		log -m "All required args are specified"
	fi
}

# Prompt User to Make Template
# --------------------
# Aks the user to initialize the project with a template
# --------------------
promptToMakeTemplate() {
	if [ $initTemp -ne 1 ]; then
		read -p "Initialize with template?(y/n) " templateResponse
		if [ ! -z $templateResponse ]; then
			templateResponse=$(echo "$templateResponse" | awk '{print tolower($0)}')
			if [ $templateResponse == 'y' ] || [ $templateResponse == 'yes' ]; then
				initTemp=1
			fi
		fi
	fi
}

# Prompt User for Packages
# --------------------
# Aks the user to install additional node packages
# --------------------
promptAdditionalPackageInstall() {

	log -n "Default packages:"
	for ((i = 0; i < ${#nodeDevDependencies[@]}; i++))
	do
		printf "%d: %s\n" $((i+1)) ${nodeDevDependencies[$i]}
	done

	log -n ""

	read -p "Install additional dev packages? (press return to continue) " val

	if [ ! -z "$val" ]; then
		if [[ $val == *[',']* ]]; then
			IFS=',' read -r -a packages <<< "$val"
		elif [[ $val == *[', ']* ]]; then
			IFS=', ' read -r -a packages <<< "$val"
		elif [[ $val == *[' ']* ]]; then
			IFS=' ' read -r -a packages <<< "$val"
		else
			read -r -a packages <<< "$val"
		fi
	fi

	if [ ${#packages[@]} -gt 0 ]; then
		for pkg in ${packages[@]}
		do
			foundNodePkg=false
			for check in ${nodeDevDependencies[@]}
			do
				if [ $check == $pkg ]; then
					foundNodePkg=true
				fi
			done
			if [ $foundNodePkg == false ]; then
				nodeDevDependencies+=("$pkg")
			fi
		done
	fi
}

# Making App Directories
# --------------------
# Makes the directories for app. The root folder is the project name specified by the user.
# --------------------
makeDirectories() {
	log -m Making directories...
	
	mkdir -p $root/{server,web/{css,img,js,partials}}

	cd $root/web/css
		mkdir -p {footer,header,main-content/{about,contact,home},page-overall,third-party}
	cd ../../..

	cd $root/web/js
		mkdir -p {controllers/{footer,header,main-content},directives,providers}
	cd ../../..

	cd $root/web/partials
		mkdir -p {directives,footer,header,main-content}
	cd ../../..	
}

# Adding Content to Files
# --------------------
# Adding content to gitignore file
# --------------------
addGitIgnore() {
	cat <<- EOF
			
			###################
			#  MAC OS files
			###################
			.DS_Store
			.AppleDouble
			.LSOverride

			# Icon must end with two \r
			Icon


			# Thumbnails
			._*

			# Files that might appear in the root of a volume
			.DocumentRevisions-V100
			.fseventsd
			.Spotlight-V100
			.TemporaryItems
			.Trashes
			.VolumeIcon.icns

			# Directories potentially created on remote AFP share
			.AppleDB
			.AppleDesktop
			Network Trash Folder
			Temporary Items
			.apdisk

			####################
			# windows OS files
			####################
			# Windows image file caches
			Thumbs.db
			ehthumbs.db

			# Folder config file
			Desktop.ini

			# Recycle Bin used on file shares
			$RECYCLE.BIN/

			# Windows Installer files
			*.cab
			*.msi
			*.msm
			*.msp

			# Windows shortcuts
			*.lnk
		EOF
}

# --------------------
# Adding content to index.html
# --------------------
addIndexHTML() {

	if [ $initTemp -eq 1 ]; then
	read -r -d '' content <<- "EOF"
		<!DOCTYPE html>
		<html>

		<head>
			\t<meta charset="utf-8">
			\t<title>[Insert Title]</title>
			\t<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>
			\t<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.3.1/angular-ui-router.min.js"></script>
			\t<link rel="stylesheet" href="css/styles-main.css" type="text/css" media="all">
			\t<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
		</head>

		<body ng-app="app">
			\t<app-header></app-header>
			\t<app-main></app-main>
			\t<app-footer></app-footer>

			\t<script src="js/app.js"></script>

			\t<script src="js/controllers/header/headerController.js"></script>
			\t<script src="js/controllers/main-content/mainController.js"></script>
			\t<script src="js/controllers/main-content/homeController.js"></script>
			\t<script src="js/controllers/main-content/aboutController.js"></script>
			\t<script src="js/controllers/main-content/contactController.js"></script>
			\t<script src="js/controllers/footer/footerController.js"></script>

			\t<script src="js/directives/header.js"></script>
			\t<script src="js/directives/main.js"></script>
			\t<script src="js/directives/home.js"></script>
			\t<script src="js/directives/about.js"></script>
			\t<script src="js/directives/contact.js"></script>
			\t<script src="js/directives/footer.js"></script>
		</body>

		<html>
		EOF
	else
		read -r -d '' content <<- "EOF"
		<!DOCTYPE html>
		<html>

		<head>
			\t<meta charset="utf-8">
			\t<title>[Insert Title]</title>
			\t<link rel="stylesheet" href="css/styles-main.css" type="text/css" media="all">
		</head>

		<body>
		</body>

		<html>
		EOF
	fi

	printf "$content"
}

# --------------------
# Adding content to styles-main.js
# --------------------
addStylesMainCSS() {
	cat <<- EOF
		/* General page styles */
		@import url('page-overall/style.css');
		
		/* 3rd party */
		/*@import url('third-party/[INSERT FILE NAME].css');*/

		/* <header> styles */
		@import url('header/style.css');
		@import url('main-content/about/style.css');
		@import url('main-content/contact/style.css');
		@import url('main-content/home/style.css');

		/* <main> and its children styles */
		@import url('main-content/style.css');

		/* <footer> styles */
		@import url('footer/style.css');

		EOF
}

# --------------------
# Adding content to app.js
# --------------------
addAppJS() {
	if [ $initTemp -eq 1 ]; then
	read -r -d '' appJsContent <<- "EOF"
		angular.module('app',['ui.router']);

		angular.module('app')
		.config(function($stateProvider, $urlRouterProvider) {
		    
		    \t$urlRouterProvider.otherwise('/home');
		    
		    \t$stateProvider
		    	\t\t.state('home', {
		            \t\t\turl: '/home',
		            \t\t\ttemplate: "<app-main-home>"
		        \t\t})
		        \t\t.state('about', {
		            \t\t\turl: '/about',
		            \t\t\ttemplate: "<app-main-about>"
		        \t\t})
		        \t\t.state('contact', {
		            \t\t\turl: '/contact',
		            \t\t\ttemplate: "<app-main-contact>"
		        \t\t});
		})
		.run(function() {
			\tconsole.log("Earthquake App started");
		});
		EOF
	fi

	printf "$appJsContent"
}

# --------------------
# Adding content to gulpfile.js
# --------------------
addGulpFile() {
	printf "var config = require(\'./gulp_config/config.js\');\n"
	for devPkg in ${nodeDevDependencies[@]}
	do
		var="var $devPkg = require('$devPkg');"
		if [[ $var == *['-']* ]]; then
			var="var ${devPkg#*-} = require('$devPkg');"
		fi
		echo $var
	done
}

# --------------------
# Adding content to config.js
# --------------------
addGulConfigFile() {
	echo -e "var config = {\n\n}\n\nmodule.exports = config;"
}

# Making Files
# --------------------
# Adding different files to the project and concatenating 
# content to them.
# --------------------
addFiles() {
	log -m "Adding content to files ..."
	touch $root/.gitignore
	touch $root/README.md
	
	touch $root/web/index.html
	
	touch $root/web/css/styles-main.css

	touch $root/web/css/header/style.css
	touch $root/web/css/main-content/style.css
	touch $root/web/css/main-content/about/style.css
	touch $root/web/css/main-content/contact/style.css
	touch $root/web/css/main-content/home/style.css
	touch $root/web/css/footer/style.css
	touch $root/web/css/page-overall/style.css
	
	touch $root/web/js/app.js

	touch $root/web/js/controllers/header/headerController.js
	touch $root/web/js/controllers/main-content/mainController.js
	touch $root/web/js/controllers/main-content/aboutController.js
	touch $root/web/js/controllers/main-content/contactController.js
	touch $root/web/js/controllers/main-content/homeController.js
	touch $root/web/js/controllers/footer/footerController.js

	touch $root/web/js/directives/about.js
	touch $root/web/js/directives/contact.js
	touch $root/web/js/directives/header.js
	touch $root/web/js/directives/footer.js
	touch $root/web/js/directives/main.js
	touch $root/web/js/directives/home.js

	touch $root/web/partials/header/header.html
	touch $root/web/partials/footer/footer.html
	touch $root/web/partials/main-content/about.html
	touch $root/web/partials/main-content/main.html
	touch $root/web/partials/main-content/contact.html
	touch $root/web/partials/main-content/home.html

	addGitIgnore > $root/.gitignore
	addIndexHTML > $root/web/index.html
	addStylesMainCSS > $root/web/css/styles-main.css
	addAppJS > $root/web/js/app.js

	addJSDirectives
	addJSControllers
	addPartials
}

# Adding Partials to Project
# --------------------
# Adding content to partials, pointing to the 
# appropriate controllers.
# --------------------
addPartials() {
	if [ $initTemp -eq 1 ]; then
		read -r -d '' partialHeader <<- "EOF"
			<header ng-controller="headerController">
				\t<div class="header-cont">
					\t\t<nav class="content home">
						\t\t\t<ul>
							\t\t\t\t<li><a ui-sref="home"><i class="fa fa-home" aria-hidden="true"></i></a></li>
						\t\t\t</ul>
					\t\t</nav>

					\t\t<nav class="content links">
						\t\t\t<ul>
							\t\t\t\t<li><a ui-sref="about">About</a></li>
							\t\t\t\t<li><a ui-sref="contact">Contact</a></li>
						\t\t\t</ul>
					\t\t</nav>
				\t</div>
			</header>
			EOF
		printf "$partialHeader" >$root/web/partials/header/header.html

		read -r -d '' partialMain <<- "EOF"
			<main ng-controller="mainController">
				\t<div class="main-cont">
					\t\t<div ui-view></div>
				\t</div>
			</main>
			EOF
		printf "$partialMain" >$root/web/partials/main-content/main.html

		read -r -d '' partialFooter <<- "EOF"
			<footer ng-controller="footerController">
				\t<div class="footer-cont">
					\t\t<ul>
						\t\t\t<li>[Project Name]</li>
						\t\t\t<li>&copy; 2016 [Author]. All rights reserverd.</li>
					\t\t</ul>
				\t</div>
			</footer>
			EOF
		printf "$partialFooter" >$root/web/partials/footer/footer.html

		read -r -d '' partialMainHome <<- "EOF"
			<section ng-controller="homeController">
				\t[HOME PARTIAL]
			</section>
			EOF
		printf "$partialMainHome" >$root/web/partials/main-content/home.html

		read -r -d '' partialMainAbout <<- "EOF"
			<section ng-controller="aboutController">
				\t[ABOUT PARTIAL]
			</section>
			EOF
		printf "$partialMainAbout" >$root/web/partials/main-content/about.html

		read -r -d '' partialMainContact <<- "EOF"
			<section ng-controller="contactController">
				\t[CONTACT PARTIAL]
			</section>
			EOF
		printf "$partialMainContact" >$root/web/partials/main-content/contact.html
	fi
}

# Adding Directives to Project
# --------------------
# Adding JS for directives to make the app 
# more modular.
# --------------------
addJSDirectives() {
	if [ $initTemp -eq 1 ]; then

		read -r -d '' directiveHeader <<- "EOF"
			angular.module('app')
			.directive('appHeader', function() {
				\treturn {
					\t\ttemplateUrl: 'partials/header/header.html'
				\t}
			});
			EOF
		printf "$directiveHeader" > $root/web/js/directives/header.js

		read -r -d '' directiveMain <<- "EOF"
			angular.module('app')
			.directive('appMain', function() {
				\treturn {
					\t\ttemplateUrl: 'partials/main-content/main.html'
				\t}
			});
			EOF
		printf "$directiveMain" > $root/web/js/directives/main.js

		read -r -d '' directiveFooter <<- "EOF"
			angular.module('app')
			.directive('appFooter', function() {
				\treturn {
					\t\ttemplateUrl: 'partials/footer/footer.html'
				\t}
			});
			EOF
		printf "$directiveFooter" > $root/web/js/directives/footer.js

		read -r -d '' directiveMainHome <<- "EOF"
			angular.module('app')
			.directive('appMainHome', function() {
				\treturn {
					\t\ttemplateUrl: 'partials/main-content/home.html'
				\t}
			});
			EOF
		printf "$directiveMainHome" > $root/web/js/directives/home.js

		read -r -d '' directiveMainAbout <<- "EOF"
			angular.module('app')
			.directive('appMainAbout', function() {
				\treturn {
					\t\ttemplateUrl: 'partials/main-content/about.html'
				\t}
			});
			EOF
		printf "$directiveMainAbout" > $root/web/js/directives/about.js

		read -r -d '' directiveMainContact <<- "EOF"
			angular.module('app')
			.directive('appMainContact', function() {
				\treturn {
					\t\ttemplateUrl: 'partials/main-content/contact.html'
				\t}
			});
			EOF
		printf "$directiveMainContact" > $root/web/js/directives/contact.js

	fi
}

# Adding Controllers to Project
# --------------------
# Adding JS for controllers to make the app 
# funcitonal.
# --------------------
addJSControllers() {
	if [ $initTemp -eq 1 ]; then
		read -r -d '' controllerHeader <<- "EOF"
			angular.module('app')
			.controller('headerController', function($scope) {
				\tconsole.log("Hello from headerController");
			});
			EOF
		printf "$controllerHeader" > $root/web/js/controllers/header/headerController.js

		read -r -d '' controllerMain <<- "EOF"
			angular.module('app')
			.controller('mainController', function($scope) {
				\tconsole.log("Hello from mainController");
			});
			EOF
		printf "$controllerMain" > $root/web/js/controllers/main-content/mainController.js

		read -r -d '' controllerFooter <<- "EOF"
			angular.module('app')
			.controller('footerController', function($scope) {
				\tconsole.log("Hello from footerController");
			});
			EOF
		printf "$controllerFooter" > $root/web/js/controllers/footer/footerController.js

		read -r -d '' controllerMainHome <<- "EOF"
			angular.module('app')
			.controller('homeController', function($scope) {
				\tconsole.log("Hello from homeController");
			});
			EOF
		printf "$controllerMainHome" > $root/web/js/controllers/main-content/homeController.js

		read -r -d '' controllerMainAbout <<- "EOF"
			angular.module('app')
			.controller('aboutController', function($scope) {
				\tconsole.log("Hello from aboutController");
			});
			EOF
		printf "$controllerMainAbout" > $root/web/js/controllers/main-content/aboutController.js

		read -r -d '' controllerMainContact <<- "EOF"
			angular.module('app')
			.controller('contactController', function($scope) {
				\tconsole.log("Hello from contactController");
			});
			EOF
		printf "$controllerMainContact" > $root/web/js/controllers/main-content/contactController.js
	fi
}

# Adding Gulp Task Runner to Project
# --------------------
# Adding gulpfile.js, congig.js package.json, 
# and installing dependencies. In addition, gulpfile.js 
# is populated with variables referencing the packages 
# that are installed as dev dependencies.
# --------------------
gulpSetup() {
	log -m "Setting up Gulp Task Runner for project ..."
	
	cd $root/web
		mkdir gulp_config
	cd ..

	touch $root/web/gulpfile.js
	touch $root/web/gulp_config/config.js

	addGulpFile > $root/web/gulpfile.js
	addGulConfigFile > $root/web/gulp_config/config.js

	cd $root/web
	# npm init
	# installNpmDependencies
	cd ..
	log -m "Gulp added"
}

# ========================================
#	SETUP
# ========================================
# findBrew

# checkBrewDependencies
# installBrewDependencies

# checkReqArgs
# promptAdditionalPackageInstall
promptToMakeTemplate

main() {
	makeDirectories
	addFiles
	gulpSetup

	log -m 'Project setup complete!'
}

# ========================================
#	RUN MAIN
# ========================================

main